<?php

/**
 * @file
 * Contains ide_at.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ide_at_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ide_at module.
    case 'help.page.ide_at':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('IDE AT module for custom things in template') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function ide_at_theme() {
  return [
    'ide_at' => [
      'render element' => 'children',
      'variables' => ['test_var' => NULL],
    ],
    'logos_swissphoto_incige_block' => [
      'render element' => 'children',
      'variables' => [
        'test_var' => NULL,
      ],
      'template' => 'block--logosswissphotoincigeagenciadeimplementacion',
    ],
    'leyenda_icdeblock' => [
      'render element' => 'children',
      'variables' => [
        'text_var' => NULL,
      ],
      'template' => 'block--leyendaicdeagenciadeimplementacion',
    ],
    'redes_sociales_block' => [
      'render element' => 'children',
      'variables' => [
        'url_twitter' => NULL,
        'url_youtube' => NULL,
      ],
      'template' => 'block--redessocialesagenciadeimplementacion',
    ],
    'creditos_block' => [
      'render element' => 'children',
      'variables' => [
        'licencia_var' => NULL,
      ],
      'template' => 'block--creditosagenciadeimplementacion',
    ],
    'banner_block' => [
      'render element' => 'children',
      'variables' => [
        'page_title_var' => NULL,
      ],
      'template' => 'block--banneragenciadeimplementacion',
    ],
  ];
}
